---
include:

  ### BISECT MATRIX (left half, usb logging snippet on all) ###
  - board: nice_nano_v2
    shield: corne_left nice_oled
    snippet: zmk-usb-logging
    cmake-args: -DCONFIG_STENO_ENGINE=n
    artifact-name: bisect_A_nosteno
  - board: nice_nano_v2
    shield: corne_left nice_oled
    snippet: zmk-usb-logging
    artifact-name: bisect_B_full
  - board: nice_nano_v2
    shield: corne_left nice_oled
    snippet: zmk-usb-logging
    cmake-args: -DCONFIG_STENO_DEBUG_NO_GATT=y
    artifact-name: bisect_C_nogatt
  - board: nice_nano_v2
    shield: corne_left nice_oled
    snippet: zmk-usb-logging
    cmake-args: -DCONFIG_STENO_DEBUG_NO_EMBED=y
    artifact-name: bisect_D_noembed
  - board: nice_nano_v2
    shield: corne_left nice_oled
    snippet: zmk-usb-logging
    cmake-args: -DCONFIG_STENO_DEBUG_NO_GATT=y -DCONFIG_STENO_DEBUG_NO_EMBED=y
    artifact-name: bisect_E_nogatt_noembed
